# Generated by Django 4.0.4 on 2022-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketservice', '0002_alter_movie_date_from_alter_movie_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(max_length=50),
        ),
    ]
