<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-05-23 16:42
=======
# Generated by Django 4.0.4 on 2022-05-23 16:50
>>>>>>> 75453ae4cb743e9405f536981a74062c16394789

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marveldcmovies', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
