# Generated by Django 4.0.4 on 2022-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marveldcmovies', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(to='marveldcmovies.comment'),
        ),
    ]
