# Generated by Django 4.0.4 on 2022-06-02 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marveldcmovies', '0018_notification_usersnotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersnotifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
