name: Build docker image and push to Docker Hub

on: [push]

jobs:

  build-and-push:
    name: Authorize, build and push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authorize
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      run: |
        cd 4\ semester/
        cd LR3\ 2022.05.07/
        cd movies_service/
        cd movies/
        docker build . 