name: Python application

on: [push]

jobs:
  runtest:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: moviesservice
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        cd 4\ semester/
        cd LR3\ 2022.05.07/
        cd movies_service/
        cd movies/  
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-django
    - name: Run migrations
      run: |
        cd 4\ semester/
        cd LR3\ 2022.05.07/
        cd movies_service/
        cd movies/ 
        python manage.py migrate
    - name: Run tests
      run: |
        cd 4\ semester/
        cd LR3\ 2022.05.07/
        cd movies_service/
        cd movies/ 
        python -m coverage run -m pytest
        python -m coverage report